DROP TABLE IF EXISTS "job" CASCADE;
DROP TABLE IF EXISTS "users" CASCADE;
DROP TABLE IF EXISTS "migrations" CASCADE;
DROP TYPE IF EXISTS "job_priority_enum" CASCADE;
DROP TYPE IF EXISTS "job_status_enum" CASCADE;
